### ISSUE TITLE
Make CNEFE data available

### ISSUE THREAD

**Issue by leoniedu** [ipeaGIT/censobr#47]
CNEFE data is quite large, so I am thinking about requiring/allowing to use the data by UF.

I forked censobr   https://github.com/leoniedu/censobr So far:

1) Download data from CNEFE 2022 (address database) process it and make it available in the data release
2) Move the release URL ("https://github.com/ipeaGIT/censobr/releases/download/") to the censobr_env 

If there is interest, I can help making this work for all UFs.

**Comment by leoniedu** [comment]
Interesting dilemma. My 2c.

Suppose you had the microdata with, in addition to the census tract, also the lat lon of each household. Where should these data live? I think you would keep it at censobr, right?

In other words. I think CNEFE is more akin to, say, population information from a census tract, than "spatial data". Although the correspondence between addresses and  households are not public, it is just the address of each household, so it belongs to censobr.

That said, there is some info available in the geobr package that I missed while writing read_cnefe. In particular the state_code -> state_abbreviations pairs.

**Comment by rafapereirabr** [comment]
Hi @leoniedu . Thanks for sharing your thoughts. Here's a quick reaction.

1. census tract-level data from Brazil's censuses are delivered via {censobr} but the spatial geometries of census tracts are delivered via {geobr}. So it's fine to have different types of census data delivered via different packages, specially considering that {geobr} and {censobr} are developed as sister packages.
2. The CNEFE data is inherently a spatial data set, beacause it is about addresses and spatial coordinates. So I would be more inclined to include it in the {geobr} package rather than on {censobr}. This is not a big issu really because eventually, {censobr} will be have {geobr} as a dependency once I fully integrate both packages.
3. IBGE does not disclose information on the census tract of microdata, and probably will never disclose info on the spatial coordinates of microdata either because these are sensitive info protected by law.

**Comment by leoniedu** [comment]
As you imply, the main use of CNEFE data, particularly given we will never have the microdata-cnefe link, is spatial. So I agree it makes more sense to include it in geobr, once it gets the cache feature.

**Comment by leoniedu** [comment]
As you imply, the main use of CNEFE data, particularly given we will never have the microdata-cnefe link, is spatial. So I agree it makes more sense to include it in geobr, once it gets the cache feature.

**Comment by rafapereirabr** [comment]
Thanks! I've opened an issue about this in the {geobr} repo https://github.com/ipeaGIT/geobr/issues/367
